---
version: "{build}"
clone_depth: 10
install:
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem
  - SET SSL_CERT_FILE=%APPVEYOR_BUILD_FOLDER%\cacert.pem
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler
  - bundler install
  - gem list --details
  - gem env

build: off
test_script:
  - bundler exec rspec spec
environment:
  COVERALLS_REPO_TOKEN: 
    secure: hfBDPUnfZ6nmf0Vrji7H30zsPBzQNGF4foiJQPWNK0Y2eiViKz/H8lOuXHPwMejH
  matrix:
    - ruby_version: "200"
    - ruby_version: "200-x64"
    # Gherkin has issues with 21 "cannot load such file -- 2.1/gherkin_lexer_en"
    #- ruby_version: "21"
    - ruby_version: "21-x64"
